### ISSUE TITLE
Failed to load Mod - Forge 1.16.4 - 35.1.13

### ISSUE THREAD

**Issue by NotoriusQ** [KnightMiner/SimpleAbsorption#2]
[crash-2021-01-02_22.38.41-fml.txt](https://github.com/KnightMiner/SimpleAbsorption/files/5761174/crash-2021-01-02_22.38.41-fml.txt)

**Comment by NotoriusQ** [comment]
I'm gonna try updating forge

**Comment by NotoriusQ** [comment]
Yep solved the problem

**Comment by KnightMiner** [comment]
I have it marked as requiring a forge version with that event, so it shouldn't have crashed, it should have told you to update, odd.
