### ISSUE TITLE
[Possible Bug] [Survive] Invalid Attributes? 

### ISSUE THREAD

**Issue by NotoriusQ** [KnightMiner/SimpleAbsorption#3]
An example of the config string I'm using:

`"attribute,generic.max_health,2;attribute,simple_absorption:absorption_max,4;attribute,simple_absorption:absorption_efficiency,4"`

Server warning when I join:

> [Server thread/WARN] [solpotato/]: Invalid attribute specified in config: simple_absorption:absorption_max
[03.01 10:06:55] [Server] [Server thread/WARN] [solpotato/]: Invalid attribute specified in config: simple_absorption:absorption_efficiency

**Comment by KnightMiner** [comment]
Try using the attribute name, not the registry name. Registry name is a Forge thing.

See https://github.com/KnightMiner/SimpleAbsorption/blob/1.16/src/main/java/knightminer/simpleabsorption/SimpleAbsorption.java#L60-L63 for attribute names.

**Comment by NotoriusQ** [comment]
"attribute,generic.max_health,2;attribute,simple_absorption.absorptionMax,4"

Is that how you mean? Or should I take out or replace "simple_absorption" with something else? not "generic"?

**Comment by Kevun1** [comment]
Hey, dev of Spice of Life: Potato edition here. This should be a bug on my end, which I'll fix in the next version.

**Comment by NotoriusQ** [comment]
Ah sweet thank you!

**Comment by Kevun1** [comment]
Ah nevermind. The issue is actually due to Simple Absorption not using the attribute system until version 1.2.0. Everything was fine on my end.

Make sure you use Simple Absorption 1.2.0, and use the registry name "simple_absorption:absorption_max" and it should work. 

For some reason, I don't actually see any absorption hearts added (even with the absorption enchant added by this mod, but this  is a separate issue)

**Comment by NotoriusQ** [comment]
Okay I grabbed the updates, and the game boots fine, loaded up a single player.
Edited the config, see below, reloaded the world and my game crashes.

{;attribute,simple_absorption:absorption_max,4"} that's how that part is supposed to look, right? Only thing I added to the config, in the first threshold.

[crash-2021-01-03_21.10.45-server.txt](https://github.com/KnightMiner/SimpleAbsorption/files/5762705/crash-2021-01-03_21.10.45-server.txt)

**Comment by KnightMiner** [comment]
@Kevun1 absorption hearts take time to appear, make sure you have enough hunger/saturation for it to regenerate.

@NotoriusQ not sure the cause of your crash. Looks like the player is missing the attribute, which implies another mod is adding new attributes to the player in a way that does not respect other mods adding attributes. Please test with just the two mods so we can determine if another mod is conflicting with the attribute.

**Comment by Kevun1** [comment]
> Okay I grabbed the updates, and the game boots fine, loaded up a single player.
> Edited the config, see below, reloaded the world and my game crashes.
> 
> {;attribute,simple_absorption:absorption_max,4"} that's how that part is supposed to look, right? Only thing I added to the config, in the first threshold.
> 
> [crash-2021-01-03_21.10.45-server.txt](https://github.com/KnightMiner/SimpleAbsorption/files/5762705/crash-2021-01-03_21.10.45-server.txt)

The config should be `"attribute,simple_absorption:absorption_max,2"` and works fine for me. The crash was caused probably by the fact that when you updated simple absorption to 1.2.0, it didn't add the attribute to the player yet when spice of life tries to access it. I've made it so that it doesn't crash when an attribute does not exist in an updated version of SOL Potato (1.0.6), and in theory everything should work again after you eat something. But everything works for me and I can't actually reproduce that crash, so it might be something else.

If you have further crashes specific to spice of life, please open another issue [here](https://github.com/Kevun1/Spice-of-Life-Potato-Edition/issues).

**Comment by NotoriusQ** [comment]
Updated, fresh install of forge.
The two didn't crash on their own, and First Aid and Survive each work on their own with them
but adding First Aid AND Survive and started to cause problems. They work when you first start the world. But if I edit the config to add base absorption hearts, I get a game crash on loading into the world.

[crash-2021-01-04_09.06.50-server.txt](https://github.com/KnightMiner/SimpleAbsorption/files/5765044/crash-2021-01-04_09.06.50-server.txt)

**Comment by NotoriusQ** [comment]
It seems to work now... I was still getting stray game crashes on loading for a minute but everything seems stable after trying to reproduce it.

Edit. Okay I think I figured out how to reproduce the crash I'm having! For real this time!!
After the config for SoLPotato and SimpleAbsorption get updated, I can reload into my world fine. But if I add Survive and do the same thing, I get a reproducible crash.

[crash-2021-01-04_09.51.54-server.txt](https://github.com/KnightMiner/SimpleAbsorption/files/5765284/crash-2021-01-04_09.51.54-server.txt)

**Comment by KnightMiner** [comment]
Survive is not visible source, so i cannot tell you if they are doing anything wrong. I'd suggest opening an issue on their tracker and tell them KnightMiner says they are registering their attributes to the player wrong most likely. Tell them to reference what Simple Absorption does.

**Comment by NotoriusQ** [comment]
Gotchya. Thanks so much for your help!

**Comment by KnightMiner** [comment]
Crosslinking for future reference: Stereowalker/Survive#43, Kevun1/Spice-of-Life-Potato-Edition#5

**Comment by NotoriusQ** [comment]
So I'm no longer having crashes but my new issue is that - only with Survive 3.1.0 and UL 3.2.2 - I can no longer apply SimpleAbsorption attributes, either via command or by mod config, like SoL:P.
It tells me "player doesn't have that attribute!"

**Comment by KnightMiner** [comment]
As I said, attribute is registered correctly, but it's not hard for a mod to break other mods attributes. This issue is on survives side, nothing I can do if they are breaking it.
